export enum PaymentAttemptStatus {
  UPLOADED = 'UPLOADED',
  PARSE_FAILED = 'PARSE_FAILED',
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  MATCHED = 'MATCHED',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}